SELECT
    shopper_id,
    CAST(dob AS DATE) AS dob,
    EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM dob) AS shopper_age,
    
    CASE 
        WHEN EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM dob) < 30 THEN '18-29'
        WHEN EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM dob) < 45 THEN '30-44'
        WHEN EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM dob) < 60 THEN '45-59'
        ELSE '60+'
    END AS age_bucket

FROM shoppers