name: 'loan_defaults'
version: '1.0.0'
config-version: 2

profile: 'loan_defaults'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  loan_defaults:
    staging:
      materialized: view
    intermediate:
      materialized: view
    marts:
      materialized: table
      loan_default_ratio:
        materialized: table
        post-hook: "ANALYZE {{ this }}"